/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tqi6LNcWow9
 */
"use client";
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

import { useState } from 'react';

export function DbConnection() {
  // State variables to store input values
  const [username, setUsername] = useState('');
  const [host, setHost] = useState('');
  const [password, setPassword] = useState('');
  const [errorMessage, setErrorMessage] = useState('');

  // Function to handle form submission
  const handleSubmit = async (e:any) => {
    e.preventDefault();

    try {
      // Send a POST request to the backend route
      const response = await fetch('/connect_db', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ username, host, password })
      });

      if (!response.ok) {
        throw new Error('Failed to connect to database');
      }

      // Clear error message if successful
      setErrorMessage('');
      // Redirect to another page or handle success
      // For example, you can use window.location.href = '/success';
    } catch (error:any) {
      // Set error message if request fails
      setErrorMessage(error.message);
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      <Card className="w-full max-w-md mx-auto">
        <CardHeader className="flex flex-col items-center space-y-2">
          <div className="flex items-center justify-center w-12 h-12 bg-red-500 rounded-full">
            <DatabaseIcon className="h-6 w-6 text-white" />
          </div>
          <CardTitle className="text-3xl">Database Connection</CardTitle>
          <CardDescription>Enter your database connection details.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="username">Username</Label>
            <Input
              id="username"
              placeholder="Enter your username"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="host">Host</Label>
            <Input
              id="host"
              placeholder="Enter your host"
              value={host}
              onChange={(e) => setHost(e.target.value)}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input
              id="password"
              placeholder="Password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>
          {errorMessage && <p className="text-red-500">{errorMessage}</p>}
        </CardContent>
        <CardFooter className="flex justify-end">
          <Button className="bg-red-500 hover:bg-red-600 text-white" type="submit">
            Connect to Database
          </Button>
        </CardFooter>
      </Card>
    </form>
  );
}



function DatabaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 0 0 21 19V5" />
      <path d="M3 12A9 3 0 0 0 21 12" />
    </svg>
  )
}
